# 実験設定ファイル
experiments:
  exp1:
    - joint_torque: [0.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [0.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [0.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [0.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [0.0]
      joint_names: ["left_knee"]
    - joint_torque: [0.0]
      joint_names: ["left_ankle"]
    - joint_torque: [0.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [0.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [0.0]
      joint_names: ["right_knee"]
    - joint_torque: [0.0]
      joint_names: ["right_ankle"]
    - joint_torque: [50.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [50.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [50.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [50.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [50.0]
      joint_names: ["left_knee"]
    - joint_torque: [50.0]
      joint_names: ["left_ankle"]
    - joint_torque: [50.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [50.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [50.0]
      joint_names: ["right_knee"]
    - joint_torque: [50.0]
      joint_names: ["right_ankle"]
    - joint_torque: [100.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [100.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [100.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [100.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [100.0]
      joint_names: ["left_knee"]
    - joint_torque: [100.0]
      joint_names: ["left_ankle"]
    - joint_torque: [100.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [100.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [100.0]
      joint_names: ["right_knee"]
    - joint_torque: [100.0]
      joint_names: ["right_ankle"]
    - joint_torque: [150.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [150.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [150.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [150.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [150.0]
      joint_names: ["left_knee"]
    - joint_torque: [150.0]
      joint_names: ["left_ankle"]
    - joint_torque: [150.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [150.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [150.0]
      joint_names: ["right_knee"]
    - joint_torque: [150.0]
      joint_names: ["right_ankle"]
    - joint_torque: [200.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [200.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [200.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [200.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [200.0]
      joint_names: ["left_knee"]
    - joint_torque: [200.0]
      joint_names: ["left_ankle"]
    - joint_torque: [200.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [200.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [200.0]
      joint_names: ["right_knee"]
    - joint_torque: [200.0]
      joint_names: ["right_ankle"]
    - joint_torque: [250.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [250.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [250.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [250.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [250.0]
      joint_names: ["left_knee"]
    - joint_torque: [250.0]
      joint_names: ["left_ankle"]
    - joint_torque: [250.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [250.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [250.0]
      joint_names: ["right_knee"]
    - joint_torque: [250.0]
      joint_names: ["right_ankle"]
    - joint_torque: [300.0]
      joint_names: ["left_hip_yaw"]
    - joint_torque: [300.0]
      joint_names: ["right_hip_yaw"]
    - joint_torque: [300.0]
      joint_names: ["left_hip_roll"]
    - joint_torque: [300.0]
      joint_names: ["left_hip_pitch"]
    - joint_torque: [300.0]
      joint_names: ["left_knee"]
    - joint_torque: [300.0]
      joint_names: ["left_ankle"]
    - joint_torque: [300.0]
      joint_names: ["right_hip_roll"]
    - joint_torque: [300.0]
      joint_names: ["right_hip_pitch"]
    - joint_torque: [300.0]
      joint_names: ["right_knee"]
    - joint_torque: [300.0]
      joint_names: ["right_ankle"]
  exp2:
    - joint_torque: [300.0]
      joint_names: ["right_ankle"]


# 基本設定（必要に応じて調整）
base_config:
  task: "Humanoidprac-v0-train"
  headless: true
  directory: "h1_flat/joint_experiment"
  python_command: "/home/satoshi/learning_practice/IsaacLab/./isaaclab.sh -p"
  num_envs: 1024
  exp_select: "exp1"


# ジョイントリスト
# left_hip_yaw_joint
# right_hip_yaw_joint
# left_hip_roll_joint
# left_hip_pitch_joint
# left_knee_joint
# left_ankle_joint
# right_hip_roll_joint
# right_hip_pitch_joint
# right_knee_joint
# right_ankle_joint
