# 実験設定ファイル
experiments:
  - joint_torque: [0]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [0]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [0]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [0]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [0]
    joint_names: ["left_knee_joint"]
  - joint_torque: [0]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [0]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [0]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [0]
    joint_names: ["right_knee_joint"]
  - joint_torque: [0]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [50]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [50]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [50]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [50]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [50]
    joint_names: ["left_knee_joint"]
  - joint_torque: [50]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [50]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [50]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [50]
    joint_names: ["right_knee_joint"]
  - joint_torque: [50]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [100]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [100]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [100]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [100]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [100]
    joint_names: ["left_knee_joint"]
  - joint_torque: [100]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [100]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [100]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [100]
    joint_names: ["right_knee_joint"]
  - joint_torque: [100]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [150]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [150]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [150]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [150]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [150]
    joint_names: ["left_knee_joint"]
  - joint_torque: [150]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [150]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [150]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [150]
    joint_names: ["right_knee_joint"]
  - joint_torque: [150]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [200]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [200]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [200]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [200]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [200]
    joint_names: ["left_knee_joint"]
  - joint_torque: [200]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [200]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [200]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [200]
    joint_names: ["right_knee_joint"]
  - joint_torque: [200]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [250]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [250]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [250]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [250]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [250]
    joint_names: ["left_knee_joint"]
  - joint_torque: [250]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [250]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [250]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [250]
    joint_names: ["right_knee_joint"]
  - joint_torque: [250]
    joint_names: ["right_ankle_joint"]
  - joint_torque: [300]
    joint_names: ["left_hip_yaw_joint"]
  - joint_torque: [300]
    joint_names: ["right_hip_yaw_joint"]
  - joint_torque: [300]
    joint_names: ["left_hip_roll_joint"]
  - joint_torque: [300]
    joint_names: ["left_hip_pitch_joint"]
  - joint_torque: [300]
    joint_names: ["left_knee_joint"]
  - joint_torque: [300]
    joint_names: ["left_ankle_joint"]
  - joint_torque: [300]
    joint_names: ["right_hip_roll_joint"]
  - joint_torque: [300]
    joint_names: ["right_hip_pitch_joint"]
  - joint_torque: [300]
    joint_names: ["right_knee_joint"]
  - joint_torque: [300]
    joint_names: ["right_ankle_joint"]

# 基本設定（必要に応じて調整）
base_config:
  task: "Humanoidprac-v0"
  headless: true
  directory: "h1_flat/joint_experiment"
  python_command: "/home/satoshi/learning_practice/IsaacLab/./isaaclab.sh -p"
  num_envs: 1024


# ジョイントリスト
# left_hip_yaw_joint
# right_hip_yaw_joint
# left_hip_roll_joint
# left_hip_pitch_joint
# left_knee_joint
# left_ankle_joint
# right_hip_roll_joint
# right_hip_pitch_joint
# right_knee_joint
# right_ankle_joint
