# 実験設定ファイル
experiments:
  - joint_torque: [400.0]
    joint_names: ["right_hip_roll"]
  
  - joint_torque: [500.0, 600.0]
    joint_names: ["right_hip_roll", "left_hip_roll"]
  
  - joint_torque: [300.0]
    joint_names: ["right_knee"]
  
  - joint_torque: [450.0, 550.0, 350.0]
    joint_names: ["right_hip_roll", "left_hip_roll", "right_knee"]

# 基本設定（必要に応じて調整）
base_config:
  task: "Humanoidprac-v0"
  headless: true
  directory: "h1_flat/joint_experiment"
  python_command: "/home/satoshi/learning_practice/IsaacLab/./isaaclab.sh -p"
  num_envs: 1024